<?php
/**
 * Created by PhpStorm.
 * User: dobrodeev
 * Date: 01.08.2018
 * Time: 20:29
 */

class CDproduct extends ShopProduct
{
    public $play;

    /**
     * CDproduct constructor.
     * @param $play
     */
    public function __construct($title, $name, $lastname, $price, $play)
    {
        parent::__construct($title, $name, $lastname, $price);
        $this->play = $play;
    }

    public function getPlay()
    {
        return $this->play;
    }

    public function getLine()
    {
//        return parent::getLine(); // TODO: Change the autogenerated stub
        $base = "$this->name"."$this->lastname"."$this->title"."$this->play";
        return $base;
    }
}