<?php
/**
 * Created by PhpStorm.
 * User: dobrodeev
 * Date: 01.08.2018
 * Time: 20:15
 */

class ShopProduct
{
    public $name;
    public $lastname;
    public $title;
    protected $price;
    public $discount;

    /**
     * ShopProduct constructor.
     * @param $name
     * @param $lastname
     * @param $price
     * @param $discount
     */
    public function __construct($name, $lastname, $title, $price)
    {
        $this->name = $name;
        $this->lastname = $lastname;
        $this->title = $title;
        $this->price = $price;
    }

    public function setDiscount($num)
    {
        $this->discount = $num;
    }

    public function getPrice()
    {
        return($this->price - $this->discount);
    }

    public function getName()
    {
        return "{$this->name}"."{$this->lastname}";
    }

    public function getLine()
    {
        $base = "$this->name"."$this->lastname"."$this->title";
        return $base;
    }
}

class CDproduct extends ShopProduct
{
    public $play;

    /**
     * CDproduct constructor.
     * @param $play
     */
    public function __construct($title, $name, $lastname, $price, $play)
    {
        parent::__construct($title, $name, $lastname, $price);
        $this->play = $play;
    }

    public function getPlay()
    {
        return $this->play;
    }

    public function getLine()
    {
//        return parent::getLine(); // TODO: Change the autogenerated stub
        $base = parent::getLine()."$this->play";
        return $base;
    }
}

class BookProduct extends ShopProduct
{
    public $page;

    /**
     * BookProduct constructor.
     * @param $page
     */
    public function __construct($title, $name, $lastname, $price, $page)
    {
        parent::__construct($title, $name, $lastname, $price);
        $this->page = $page;
    }

    public function getPages()
    {
        return $this->page;
    }

    public function getLine()
    {
//        return parent::getLine(); // TODO: Change the autogenerated stub
        $base = parent::getLine()."$this->page";
        return $base;
    }
}

$product1 = new BookProduct('Iron World', 'Man', 'Surname', 167, 87);
$product2 = new CDproduct('Iron World', 'Man', 'Surname', 329, 46);
$product1->setDiscount(0.5);
echo $product1->getPrice();
echo $product1->getLine();